### ISSUE TITLE
jamfpro_account_group doesn't recognize "Users" object permission

### ISSUE THREAD

**Issue by FSDeWolf** [deploymenttheory/terraform-provider-jamfpro#184]
Mostly semantic , but this module doesn't recognize "Read Users" (or Create/Update/Delete). It does recognize it as User, which isn't how it looks in Jamf.

![image](https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/110746136/d4474ec8-fe48-407e-af8f-987f330215de)

**Comment by ShocOne** [comment]
Which resource are you referring to specifically? Thanks

**Comment by ShocOne** [comment]
Hi there,

Performing a `GET` on the endpoint `"/api/v1/api-role-privileges"` , ( jamf pro ver 11.3) states that the permissions are not pluralised and are singular in form. e.g

![image](https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/62835948/cc5b1253-90ff-491f-89fb-fd46bb1333b3)

and

![image](https://github.com/deploymenttheory/terraform-provider-jamfpro/assets/62835948/86a90bf5-2364-44d0-9523-9ca5bdc7b0ef)

etc. Therefore, for a `POST` request to be successful, we will be sticking with what the api actually requires rather than what the gui states. Clearly a typo on jamf's side :)
