### ISSUE TITLE
Feature Request: Add support for DDM managed software updates

### ISSUE THREAD

**Issue by mhrono** [deploymenttheory/terraform-provider-jamfpro#212]
Relevant jamf API docs: https://developer.jamf.com/jamf-pro/reference/get_v1-managed-software-updates-available-updates

Why? While this functionality in jamf is still tagged as `beta`, Apple has made some serious improvements to the reliability of managed software updates, particularly when using the new DDM framework. The ability to manage these in code would be awesome, and would pair really well with other update-related automations, like [sofa](https://github.com/macadmins/sofa).

**Comment by ShocOne** [comment]
Hi there, at present we have beta url endpoint coverage for this within the jamfpro sdk. [go-api-sdk-jamfpro](https://github.com/deploymenttheory/go-api-sdk-jamfpro/blob/main/sdk/jamfpro/jamfproapi_managed_software_updates.go) Which would make this fairly easily to implement based on the current data model. 

However from my side there's no current plans within the tf provider to support beta jamfpro url endpoints because of the likelihood of reworking. Would be open to a discussion via DM on the slack admins. Thanks

**Comment by ShocOne** [comment]
Hi @mhrono , are you happy that we close this ? It's been supported within the provider for a number of versions now. Please confirm if you have any other objections, else I'll assume the feat request has been met. Many thanks.

**Comment by ShocOne** [comment]
Closing. Will reopen if required.
