### ISSUE TITLE
Enhancement: implement API calls for POST /v1/icon and GET /v1/icon/{id}

### ISSUE THREAD

**Issue by ecanault** [deploymenttheory/terraform-provider-jamfpro#473]
Hi,

Implementation of API calls for **POST** `/v1/icon` and **GET** `/v1/icon/{id}` are missing in the provider to be able to manage icons resources for Self Service in policies for example.

Is it possible to add this?

Thanks,
Emmanuel

**Comment by ShocOne** [comment]
hi there, icons are unsupported at the present. the api behind this is awful, and doesn't behave as one would expect it to when trying to interact with it. numerous attempts have been made previously to get this working with the sdk by multiple people and i've concluded that Jamf need to fix this api before i try another attempt at this.

**Comment by ecanault** [comment]
Hi,

Thanks for your feedback.
I close this one for the moment, hoping that Jamf will fix it  one day!

Emmanuel

**Comment by ShocOne** [comment]
hi there, quick update, i finally got this working. it's now within release v0.6.0. The issue was with how i had build the http client, it was incorrectly base64 encoding the content being sent to jamf and this is why icons were not uploading correctly. now there's the option to base64 encode or send raw bytes. this has been resolved and therefore icons has been added to the provider. incidentally this was also the root cause of why packages were getting corrupted.

**Comment by ecanault** [comment]
Thanks for that, I will look at it asap 🙂
